# Generated by Django 3.1 on 2020-08-14 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='time',
            field=models.DateField(default=datetime.datetime(2020, 8, 14, 19, 13, 14, 528410)),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(max_length=122),
        ),
    ]
