# Generated by Django 3.1 on 2020-08-14 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200814_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.DateField(default=datetime.datetime(2020, 8, 14, 21, 14, 17, 82173)),
        ),
    ]
