# Generated by Django 3.1 on 2020-08-14 21:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200814_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
